<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="haile" failures="5" tests="7" name="TestAddController" time="1.877" errors="0" timestamp="2021-12-04T11:54:21 ICT">
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC01_Failed" time="0.031">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC01_Failed()[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC01_Failed()[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC01_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC02_Failed" time="0.001">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC02_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC02_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC02_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC03_Failed" time="0.001">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC03_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC03_Failed(java.lang.String)[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC03_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC04_Failed" time="0.002">
    <failure type="org.testng.TestException" message="
Method AddControllerTest.adduserTest_TC04_Failed()[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception">
      <![CDATA[org.testng.TestException: 
Method AddControllerTest.adduserTest_TC04_Failed()[pri:0, instance:testController.AddControllerTest@554e218] should have thrown an exception of type class java.lang.Exception
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- adduserTest_TC04_Failed -->
  <testcase classname="testController.AddControllerTest" name="adduserTest_TC05_Success" time="0.001"/>
  <testcase classname="testController.AddControllerTest" name="getcodeTest" time="0.011"/>
  <testcase classname="testController.AddControllerTest" name="getlistuserTest" time="0.027">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;0&amp;gt; but was:&amp;lt;1&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<0> but was:<1>
at testController.AddControllerTest.getlistuserTest(AddControllerTest.java:107)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getlistuserTest -->
</testsuite> <!-- TestAddController -->
