<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="haile" failures="0" tests="20" name="testModel.DethiTest" time="0.021" errors="3" timestamp="2021-12-05T23:34:42 ICT" skipped="0">
  <testcase classname="testModel.DethiTest" name="getLoaide_idTest_TC_07" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getTrangThaiTest_TC_14" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setIdTest_TC_17" time="0.000"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setLoaide_idTest_TC_18" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setTrangThaiTest" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getEmailTest_TC_02" time="0.002"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setTimerTest_TC_19" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setLoaide_idTest_TC_09" time="0.001">
    <error message="
Method DethiTest.setLoaide_idTest_TC_09()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method DethiTest.setLoaide_idTest_TC_09()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setLoaide_idTest_TC_09 -->
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setTimerTest_TC_12" time="0.001">
    <error message="
Method DethiTest.setTimerTest_TC_12()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method DethiTest.setTimerTest_TC_12()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setTimerTest_TC_12 -->
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getEmailTest_TC_01" time="0.005"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getTimerTest_TC_10" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getEmailTest_TC_03" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getTimerTest_TC_11" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setEmailTest_TC_16" time="0.000"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getIdTest_TC_04" time="0.000"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getIdTest_TC_05" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getTrangThaiTest_TC_15" time="0.001"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getLoaide_idTest_TC_08" time="0.000"/>
  <system-out/>
  <testcase classname="testModel.DethiTest" name="setIdTest_TC_06" time="0.001">
    <error message="
Method DethiTest.setIdTest_TC_06()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Method DethiTest.setIdTest_TC_06()[pri:0, instance:testModel.DethiTest@65d09a04] should have thrown an exception of type class java.lang.Exception
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- setIdTest_TC_06 -->
  <system-out/>
  <testcase classname="testModel.DethiTest" name="getTrangThaiTest_TC_13" time="0.001"/>
  <system-out/>
</testsuite> <!-- testModel.DethiTest -->
